version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - cd TempoDeckSpring
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'TempoDeckSpring/target'