version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - cd p2-backend/TempoDeckSpring
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'p2-backend/TempoDeckSpring/target'