-- This hashes data. To use, call function crypt(''stringToBeHashedSuchAsPassword', gen_salt('bf',7)) --
-- useful pgcrypto resource: https://til.hashrocket.com/posts/a2170ba6b0-salt-and-hash-a-password-with-postgres-pgcrypto --
-- Also maybe read up on password hashing. We're using the BlowFish algorithm hashed 7 times, which is pretty hard to beat --
CREATE EXTENSION pgcrypto;

INSERT INTO td_role (role)
    VALUES ('Administrator'), ('Moderator'), ('User');

INSERT INTO td_user (username, password, email, first_name, last_name, role_id)
VALUES ('cbprosser', crypt('password', gen_salt('bf',7)), 'cbprosser@tempodeck.com', 'chris', 'prosser', (SELECT role_id FROM td_role WHERE role='Administrator')),
	   ('mjarsenault', crypt('password', gen_salt('bf',7)), 'mjarsenault@tempodeck.com', 'matt', 'arsenault', (SELECT role_id FROM td_role WHERE role='Administrator')),
	   ('nbray', crypt('password', gen_salt('bf',7)), 'nbray@tempodeck.com', 'nicholas', 'bray', (SELECT role_id FROM td_role WHERE role='Administrator')),
	   ('lescobosasainz', crypt('password', gen_salt('bf',7)), 'lescobosa@tempodeck.com', 'luis', 'escobosa', (SELECT role_id FROM td_role WHERE role='Administrator')),
	   ('hatebear', crypt('password', gen_salt('bf',7)), 'deathntaxes@tempodeck.com', 'Thalia', '', (SELECT role_id FROM td_role WHERE role='Moderator')),
	   ('no.x.spells', crypt('password', gen_salt('bf',7)), 'fairmagiconly@tempodeck.com', 'Gaddock', 'Teeg', (SELECT role_id FROM td_role WHERE role='Moderator')),
	   ('monoUDelver', crypt('password', gen_salt('bf',7)), 'delver.of.secrets@tempodeck.com', '', '', (SELECT role_id FROM td_role WHERE role='User')),
	   ('simicrulezzz', crypt('password', gen_salt('bf',7)), 'pszegana@tempodeck.com', '', '', (SELECT role_id FROM td_role WHERE role='User'));

INSERT INTO td_formats (format)
VALUES ('Commander'), ('standard'), ('Modern'), ('Pauper'), ('Brawl'), ('Legacy'), ('Vintage');


INSERT INTO td_deck (deck_author, deck_name, deck_description, deck_format)
VALUES ((SELECT user_id FROM td_user WHERE username = 'cbprosser'), 'deck1', 'no description', (SELECT format_id FROM td_formats WHERE format='standard')),
	   ((SELECT user_id FROM td_user WHERE username = 'hatebear'), 'deck1', 'no description', (SELECT format_id FROM td_formats WHERE format='standard')),
	   ((SELECT user_id FROM td_user WHERE username = 'monoUDelver'), 'deck1', 'no description', (SELECT format_id FROM td_formats WHERE format='standard')),
	   ((SELECT user_id FROM td_user WHERE username = 'no.x.spells'), 'deck1', 'no description', (SELECT format_id FROM td_formats WHERE format='standard'));

INSERT INTO td_collection (collection_author, collection_name, collection_description)
VALUES ((SELECT user_id FROM td_user WHERE username = 'cbprosser'), 'collection1', 'no description'),
	   ((SELECT user_id FROM td_user WHERE username = 'hatebear'), 'collection1', 'no description'),
	   ((SELECT user_id FROM td_user WHERE username = 'monoUDelver'), 'collection1', 'no description'),
	   ((SELECT user_id FROM td_user WHERE username = 'no.x.spells'), 'collection1', 'no description');

INSERT INTO td_deck_cards (deck_id, deck_card, deck_card_amount)
VALUES (1, 'Abnormal Endurance', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Absorb', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Academy Drake', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Academy Journeymage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Act of Treason', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adamant Will', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adanto Vanguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adeliz, the Cinder Wind', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Admiral Beckett Brass', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Admiral''s Order', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adventurous Impulse', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aegis of the Heavens', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aerial Assault', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aerial Engineer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aeromunculus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aesthir Glider', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aether Gust', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aethershield Artificer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aether Tunnel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Affectionate Indrik', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Agent of Treachery', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aggressive Mammoth', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aggressive Urge', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Agonizing Syphon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ahn-Crop Invader', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aid the Fallen', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Air Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Adversary of Tyrants', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Inspiring Leader', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Influence', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Last Stand', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Pridemate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Strength of the Pride', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Welcome', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, the Greathearted', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Wise Counselor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Alpine Moon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amaranthine Wall', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amplifire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amulet of Safekeeping', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancestral Blade', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancient Animus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancient Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Exaltation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Gift', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Guardian', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of Grace', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of the Dawn', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of Vitality', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angler Turtle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, Captain of Chaos', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, Minotaur Pirate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Ambusher', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Fury', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Marauders', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Rampage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, the Flame-Chained', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Anointed Deacon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
	(2, 'Anticipate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Anvilwrought Raptor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Apex of Power', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Apostle of Purifying Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Applied Biomancy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aquatic Incursion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arbor Armament', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arboreal Grazer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arboretum Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcades, the Strategist', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Adaptation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Encyclopedia', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Flight', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arch of Orazca', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Archway Angel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arclight Phoenix', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arguel''s Blood Fast // Temple of Aclazotz', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arisen Gorgon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arlinn''s Wolf', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arlinn, Voice of the Pack', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arrester''s Admonition', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arrester''s Zeal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arterial Flow', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Artful Takedown', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Artificer''s Assistant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arvad the Cursed', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aryel, Knight of Windgrace', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashes of the Abhorrent', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashiok, Dream Render', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashiok''s Skulker', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Assassin''s Trophy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Assure // Assemble', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atemsis, All-Seeing', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Attendant of Vraska', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atzocan Archer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atzocan Seer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Audacious Thief', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Augur of Bolas', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aurelia, Exemplar of Justice', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Eternal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Sentry', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Wind Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aviation Pioneer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awakened Amalgam', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awakening of Vitu-Ghazi', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awaken the Erstwhile', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Axebane Beast', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Axis of Mortality', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Guildgate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Knight-Arbiter', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Locket', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Skyguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azor''s Gateway // Sanctum of the Sun', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azor, the Lawbringer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Baffling End', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Bag of Holding', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Baird, Steward of Argive', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Baloth Gorger', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Band Together', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Banefire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Banehound', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bankrupt in Blood', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barging Sergeant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barkhide Troll', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barony Vampire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barrier of Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bartizan Bats', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Basilica Bell-Haunt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bastion Enforcer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Battalion Foot Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Battlefield Promotion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beacon Bolt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beamsplitter Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beast Whisperer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bedeck // Bedazzle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bedevil', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Befuddle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Belligerent Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bellowing Aegisaur', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benalish Honor Guard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benalish Marshal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benthic Biomancer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bioessence Hydra', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biogenic Ooze', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biogenic Upgrade', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biomancer''s Familiar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Binding', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Rebirth', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of the Bloodstained', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Wings', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop''s Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blackblade Reforged', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bladebrand', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blade Instructor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blade Juggler', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blanchwood Armor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blast Zone', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blazing Hope', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bleeding Edge', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blessed Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blessing of Belzenlok', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blightbeetle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blight Keeper', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blindblast', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blinding Fog', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blink of an Eye', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Burglar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodcrazed Paladin', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Crypt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Divination', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodfell Caves', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood for Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodmist Infiltrator', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Operative', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodsoaked Altar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodstone Goblin', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Sun', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
	(4, 'Abnormal Endurance', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Absorb', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Academy Drake', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Academy Journeymage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Act of Treason', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adamant Will', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adanto Vanguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adeliz, the Cinder Wind', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Admiral Beckett Brass', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Admiral''s Order', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adventurous Impulse', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aegis of the Heavens', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aerial Assault', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aerial Engineer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aeromunculus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aesthir Glider', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aether Gust', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aethershield Artificer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Anticipate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Anvilwrought Raptor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Apex of Power', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Apostle of Purifying Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Applied Biomancy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aquatic Incursion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arbor Armament', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arboreal Grazer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arboretum Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcades, the Strategist', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Adaptation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Encyclopedia', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Flight', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arch of Orazca', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Archway Angel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arclight Phoenix', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arguel''s Blood Fast // Temple of Aclazotz', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arisen Gorgon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arlinn''s Wolf', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arlinn, Voice of the Pack', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arrester''s Admonition', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arrester''s Zeal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arterial Flow', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Artful Takedown', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barging Sergeant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barkhide Troll', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barony Vampire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barrier of Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bartizan Bats', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Basilica Bell-Haunt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bastion Enforcer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Battalion Foot Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Battlefield Promotion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beacon Bolt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beamsplitter Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beast Whisperer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bedeck // Bedazzle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bedevil', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Befuddle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Belligerent Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bellowing Aegisaur', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benalish Honor Guard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benalish Marshal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benthic Biomancer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bioessence Hydra', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Biogenic Ooze', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10));

INSERT INTO td_collection_cards (collection_id, collection_card, collection_card_amount)
VALUES (1, 'Abnormal Endurance', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Absorb', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Academy Drake', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Academy Journeymage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Act of Treason', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adamant Will', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adanto Vanguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adeliz, the Cinder Wind', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Admiral Beckett Brass', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Admiral''s Order', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Adventurous Impulse', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aegis of the Heavens', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aerial Assault', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aerial Engineer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aeromunculus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aesthir Glider', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aether Gust', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aethershield Artificer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aether Tunnel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Affectionate Indrik', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Agent of Treachery', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aggressive Mammoth', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aggressive Urge', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Agonizing Syphon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ahn-Crop Invader', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Aid the Fallen', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Air Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Adversary of Tyrants', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Inspiring Leader', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Influence', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Last Stand', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Pridemate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Strength of the Pride', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani''s Welcome', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, the Greathearted', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ajani, Wise Counselor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Alpine Moon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amaranthine Wall', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amplifire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Amulet of Safekeeping', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancestral Blade', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancient Animus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Ancient Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Exaltation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Gift', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angelic Guardian', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of Grace', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of the Dawn', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angel of Vitality', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angler Turtle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, Captain of Chaos', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, Minotaur Pirate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Ambusher', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Fury', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Marauders', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath''s Rampage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Angrath, the Flame-Chained', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (1, 'Anointed Deacon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
	(2, 'Anticipate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Anvilwrought Raptor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Apex of Power', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Apostle of Purifying Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Applied Biomancy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aquatic Incursion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arbor Armament', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arboreal Grazer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arboretum Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcades, the Strategist', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Adaptation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Encyclopedia', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arcane Flight', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arch of Orazca', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Archway Angel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arclight Phoenix', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arguel''s Blood Fast // Temple of Aclazotz', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arisen Gorgon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arlinn''s Wolf', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arlinn, Voice of the Pack', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arrester''s Admonition', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arrester''s Zeal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arterial Flow', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Artful Takedown', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Artificer''s Assistant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Arvad the Cursed', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aryel, Knight of Windgrace', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashes of the Abhorrent', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashiok, Dream Render', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Ashiok''s Skulker', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Assassin''s Trophy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Assure // Assemble', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atemsis, All-Seeing', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Attendant of Vraska', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atzocan Archer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Atzocan Seer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Audacious Thief', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Augur of Bolas', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aurelia, Exemplar of Justice', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Eternal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Sentry', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aven Wind Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Aviation Pioneer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awakened Amalgam', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awakening of Vitu-Ghazi', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Awaken the Erstwhile', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Axebane Beast', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Axis of Mortality', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Guildgate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Knight-Arbiter', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Locket', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azorius Skyguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azor''s Gateway // Sanctum of the Sun', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Azor, the Lawbringer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Baffling End', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Bag of Holding', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (2, 'Baird, Steward of Argive', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Baloth Gorger', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Band Together', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Banefire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Banehound', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bankrupt in Blood', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barging Sergeant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barkhide Troll', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barony Vampire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Barrier of Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bartizan Bats', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Basilica Bell-Haunt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bastion Enforcer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Battalion Foot Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Battlefield Promotion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beacon Bolt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beamsplitter Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Beast Whisperer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bedeck // Bedazzle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bedevil', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Befuddle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Belligerent Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bellowing Aegisaur', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benalish Honor Guard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benalish Marshal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Benthic Biomancer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bioessence Hydra', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biogenic Ooze', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biogenic Upgrade', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Biomancer''s Familiar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Binding', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Rebirth', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of the Bloodstained', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop of Wings', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bishop''s Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blackblade Reforged', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bladebrand', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blade Instructor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blade Juggler', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blanchwood Armor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blast Zone', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blazing Hope', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bleeding Edge', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blessed Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blessing of Belzenlok', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blightbeetle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blight Keeper', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blindblast', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blinding Fog', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blink of an Eye', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Burglar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodcrazed Paladin', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Crypt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Divination', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodfell Caves', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood for Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodmist Infiltrator', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Operative', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodsoaked Altar', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Bloodstone Goblin', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (3, 'Blood Sun', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
	(4, 'Abnormal Endurance', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Absorb', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Academy Drake', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Academy Journeymage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Act of Treason', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adamant Will', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adanto Vanguard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adeliz, the Cinder Wind', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Admiral Beckett Brass', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Admiral''s Order', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Adventurous Impulse', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aegis of the Heavens', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aerial Assault', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aerial Engineer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aeromunculus', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aesthir Glider', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aether Gust', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aethershield Artificer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Anticipate', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Anvilwrought Raptor', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Apex of Power', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Apostle of Purifying Light', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Applied Biomancy', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Aquatic Incursion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arbor Armament', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arboreal Grazer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arboretum Elemental', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcades, the Strategist', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Adaptation', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Encyclopedia', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arcane Flight', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arch of Orazca', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Archway Angel', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arclight Phoenix', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arguel''s Blood Fast // Temple of Aclazotz', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arisen Gorgon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arlinn''s Wolf', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arlinn, Voice of the Pack', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arrester''s Admonition', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arrester''s Zeal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Arterial Flow', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Artful Takedown', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barging Sergeant', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barkhide Troll', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barony Vampire', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Barrier of Bones', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bartizan Bats', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Basilica Bell-Haunt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bastion Enforcer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Battalion Foot Soldier', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Battlefield Promotion', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beacon Bolt', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beamsplitter Mage', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Beast Whisperer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bedeck // Bedazzle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bedevil', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Befuddle', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Belligerent Brontodon', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bellowing Aegisaur', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benalish Honor Guard', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benalish Marshal', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Benthic Biomancer', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Bioessence Hydra', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10)),
    (4, 'Biogenic Ooze', (SELECT floor(random() * 10 + 1)::integer AS RAND_1_10));