server:
  port: ${PORT:8012}
  
spring:
  application:
    name: tempodeck-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: hunter2
    url: jdbc:postgresql://localhost:5432/${TD_API_NAME:td_api}
    username: postgres
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${TD_API_SCHEMA:public}
    show-sql: false
    
